// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID              int32          `json:"id"`
	Username        string         `json:"username"`
	Role            int32          `json:"role"`
	CreatedAt       time.Time      `json:"created_at"`
	EmailAddress    sql.NullString `json:"email_address"`
	IsEmailVerified sql.NullBool   `json:"is_email_verified"`
	PictureUrl      sql.NullString `json:"picture_url"`
}
