version: "3"
services:
  backend:
    build: backend/
    restart: always
    container_name: app-docker
    ports:
      - 8848:8848
    environment:
      - HOST_IP=${HOST_IP}
    env_file:
      - .env
    volumes:
      - appdata:/appdata
  nginx:
    restart: always
    container_name: app-nginx
    build: frontend/
    ports:
      - 5678:80
    depends_on:
      - backend
    volumes:
      - appdata:/appdata
volumes:
  appdata:
