version: "3"
services:
  backend:
    build: backend/
    restart: always
    container_name: app-docker
    ports:
      - 8848:8848
    environment:
      - HOST_IP=${HOST_IP}
    env_file:
      - .env
    volumes:
      - appdata:/appdata
      - downloads:/downloads
  nginx:
    restart: always
    container_name: app-nginx
    build: frontend/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:      
      - appdata:/appdata
  mbtileserver:
    image: consbio/mbtileserver:0.9.0
    container_name: mbtileserver
    # entrypoint: /mbtileserver  --enable-fs-watch -d /appdata
    entrypoint: >
      sh -c "mkdir -p /appdata/beforetiles /appdata/aftertiles  && exec /mbtileserver  --enable-fs-watch -d /appdata"
    restart: always
    depends_on:
      - backend
    ports:
    - 8080:8000
    volumes:
      - appdata:/appdata


volumes:
  appdata:
  downloads:
