version: "3"
services:
  postgres:
    container_name: before-after-db
    image: mdillon/postgis:11
    restart: always
    environment:
      - POSTGRES_USER=baato
      - POSTGRES_PASSWORD=baato
      - POSTGRES_DB=before-after
    volumes:
      - data/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: "."
      dockerfile: "./Dockerfile.backend"
    container_name: backend
    entrypoint: ["/start.sh"]
    restart: always
    ports:
      - 8848:8848
    volumes:
      - appdata:/appdata
      - downloads:/downloads

  migration:
    image: before-after_backend:latest
    container_name: migration
    restart: on-failure
    command: migrate -path ./backend/server/db/migration -database postgresql://baato:baato@postgres:5432/before-after?sslmode=disable -verbose up
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    restart: always
    container_name: app-nginx
    build: frontend/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - appdata:/appdata

volumes:
  appdata:
  downloads:
  data/postgres:
